//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculator1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.CalculationSoap")]
    public interface CalculationSoap {
        
        // CODEGEN: Generating message contract since element name AdditionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Addition", ReplyAction="*")]
        Calculator1.ServiceReference1.AdditionResponse Addition(Calculator1.ServiceReference1.AdditionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Addition", ReplyAction="*")]
        System.Threading.Tasks.Task<Calculator1.ServiceReference1.AdditionResponse> AdditionAsync(Calculator1.ServiceReference1.AdditionRequest request);
        
        // CODEGEN: Generating message contract since element name GetCalculationsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCalculations", ReplyAction="*")]
        Calculator1.ServiceReference1.GetCalculationsResponse GetCalculations(Calculator1.ServiceReference1.GetCalculationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCalculations", ReplyAction="*")]
        System.Threading.Tasks.Task<Calculator1.ServiceReference1.GetCalculationsResponse> GetCalculationsAsync(Calculator1.ServiceReference1.GetCalculationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Subtraction", ReplyAction="*")]
        int Subtraction(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Subtraction", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SubtractionAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Muliplication", ReplyAction="*")]
        int Muliplication(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Muliplication", ReplyAction="*")]
        System.Threading.Tasks.Task<int> MuliplicationAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Division", ReplyAction="*")]
        int Division(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Division", ReplyAction="*")]
        System.Threading.Tasks.Task<int> DivisionAsync(int x, int y);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdditionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Addition", Namespace="http://tempuri.org/", Order=0)]
        public Calculator1.ServiceReference1.AdditionRequestBody Body;
        
        public AdditionRequest() {
        }
        
        public AdditionRequest(Calculator1.ServiceReference1.AdditionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdditionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int x;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int y;
        
        public AdditionRequestBody() {
        }
        
        public AdditionRequestBody(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdditionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdditionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Calculator1.ServiceReference1.AdditionResponseBody Body;
        
        public AdditionResponse() {
        }
        
        public AdditionResponse(Calculator1.ServiceReference1.AdditionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdditionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AdditionResult;
        
        public AdditionResponseBody() {
        }
        
        public AdditionResponseBody(string AdditionResult) {
            this.AdditionResult = AdditionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCalculationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCalculations", Namespace="http://tempuri.org/", Order=0)]
        public Calculator1.ServiceReference1.GetCalculationsRequestBody Body;
        
        public GetCalculationsRequest() {
        }
        
        public GetCalculationsRequest(Calculator1.ServiceReference1.GetCalculationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCalculationsRequestBody {
        
        public GetCalculationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCalculationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCalculationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Calculator1.ServiceReference1.GetCalculationsResponseBody Body;
        
        public GetCalculationsResponse() {
        }
        
        public GetCalculationsResponse(Calculator1.ServiceReference1.GetCalculationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCalculationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Calculator1.ServiceReference1.ArrayOfString GetCalculationsResult;
        
        public GetCalculationsResponseBody() {
        }
        
        public GetCalculationsResponseBody(Calculator1.ServiceReference1.ArrayOfString GetCalculationsResult) {
            this.GetCalculationsResult = GetCalculationsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculationSoapChannel : Calculator1.ServiceReference1.CalculationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculationSoapClient : System.ServiceModel.ClientBase<Calculator1.ServiceReference1.CalculationSoap>, Calculator1.ServiceReference1.CalculationSoap {
        
        public CalculationSoapClient() {
        }
        
        public CalculationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Calculator1.ServiceReference1.AdditionResponse Calculator1.ServiceReference1.CalculationSoap.Addition(Calculator1.ServiceReference1.AdditionRequest request) {
            return base.Channel.Addition(request);
        }
        
        public string Addition(int x, int y) {
            Calculator1.ServiceReference1.AdditionRequest inValue = new Calculator1.ServiceReference1.AdditionRequest();
            inValue.Body = new Calculator1.ServiceReference1.AdditionRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            Calculator1.ServiceReference1.AdditionResponse retVal = ((Calculator1.ServiceReference1.CalculationSoap)(this)).Addition(inValue);
            return retVal.Body.AdditionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Calculator1.ServiceReference1.AdditionResponse> Calculator1.ServiceReference1.CalculationSoap.AdditionAsync(Calculator1.ServiceReference1.AdditionRequest request) {
            return base.Channel.AdditionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Calculator1.ServiceReference1.AdditionResponse> AdditionAsync(int x, int y) {
            Calculator1.ServiceReference1.AdditionRequest inValue = new Calculator1.ServiceReference1.AdditionRequest();
            inValue.Body = new Calculator1.ServiceReference1.AdditionRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            return ((Calculator1.ServiceReference1.CalculationSoap)(this)).AdditionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Calculator1.ServiceReference1.GetCalculationsResponse Calculator1.ServiceReference1.CalculationSoap.GetCalculations(Calculator1.ServiceReference1.GetCalculationsRequest request) {
            return base.Channel.GetCalculations(request);
        }
        
        public Calculator1.ServiceReference1.ArrayOfString GetCalculations() {
            Calculator1.ServiceReference1.GetCalculationsRequest inValue = new Calculator1.ServiceReference1.GetCalculationsRequest();
            inValue.Body = new Calculator1.ServiceReference1.GetCalculationsRequestBody();
            Calculator1.ServiceReference1.GetCalculationsResponse retVal = ((Calculator1.ServiceReference1.CalculationSoap)(this)).GetCalculations(inValue);
            return retVal.Body.GetCalculationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Calculator1.ServiceReference1.GetCalculationsResponse> Calculator1.ServiceReference1.CalculationSoap.GetCalculationsAsync(Calculator1.ServiceReference1.GetCalculationsRequest request) {
            return base.Channel.GetCalculationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Calculator1.ServiceReference1.GetCalculationsResponse> GetCalculationsAsync() {
            Calculator1.ServiceReference1.GetCalculationsRequest inValue = new Calculator1.ServiceReference1.GetCalculationsRequest();
            inValue.Body = new Calculator1.ServiceReference1.GetCalculationsRequestBody();
            return ((Calculator1.ServiceReference1.CalculationSoap)(this)).GetCalculationsAsync(inValue);
        }
        
        public int Subtraction(int x, int y) {
            return base.Channel.Subtraction(x, y);
        }
        
        public System.Threading.Tasks.Task<int> SubtractionAsync(int x, int y) {
            return base.Channel.SubtractionAsync(x, y);
        }
        
        public int Muliplication(int x, int y) {
            return base.Channel.Muliplication(x, y);
        }
        
        public System.Threading.Tasks.Task<int> MuliplicationAsync(int x, int y) {
            return base.Channel.MuliplicationAsync(x, y);
        }
        
        public int Division(int x, int y) {
            return base.Channel.Division(x, y);
        }
        
        public System.Threading.Tasks.Task<int> DivisionAsync(int x, int y) {
            return base.Channel.DivisionAsync(x, y);
        }
    }
}
